prometheus:
  namespace: monitoring
dashboards:
  mariadb:
    name: mariadb
    file: mariadb.json
    enable: false
  elasticsearch:
    name: elasticsearch
    file: elasticsearch.json
    enable: true
  mongodb:
    name: mongodb
    file: mongodb.json
    enable: false
  postgresqlha:
    name: postgresqlha
    file: postgresqlha.json
    enable: false
  mariadbgal:
    name: mariadbgal
    file: mariadbgal.json
    enable: false